### ISSUE TITLE
Unable to play video streamed using piping server on safari.

### ISSUE THREAD

**Issue by kkanhiya** [nwtgck/piping-server#171] opened 2019-07-26 07:16 UTC
[INFO] Waiting for 1 receiver(s)...
[INFO] A receiver was connected.
[INFO] Start sending to 1 receiver(s)!
[INFO] All receiver(s) was/were closed halfway.

**Comment by nwtgck** [comment] 2019-07-27 05:33
@kkanhiya 
Thank you for reporting. Could you give me more detail? Could you give me your command and video if possible?

**Comment by nwtgck** [comment] 2019-07-27 05:40
I tried to stream a video in Safari, but I could not. However, in Chrome I could in the following commands. 

```bash
# Twice
$  cat ray.mp4 | pv | curl -T - -H 'Content-Type: video/mp4' https://piping.ml/myvide
# Open  https://piping.ml/myvide in the browser
# Cancel the command above by the browser
$  cat ray.mp4 | pv | curl -T - -H 'Content-Type: video/mp4' https://piping.ml/myvide
```

The first command will be canceled by a browser. Then, you can type the same command again.

**Comment by nwtgck** [comment] 2019-07-27 06:00
@kkanhiya I found the reason why Safari doesn't play a video. That's because Safari needs HTTP Range Request. As you know, Piping Server streams data, so it can not support HTTP Range.
I found a Japanese reference, I'm looking for an English one.

<https://qiita.com/gecko655/items/110373a6c88177d23126> (ja)

**Comment by kkanhiya** [comment] 2019-07-29 03:45
@nwtgck looks like this is a range problem from safari end but I am still confused why server stops sending video?? 

Is there any solution to the safari range request problem??

**Comment by kkanhiya** [comment] 2019-07-29 06:42
I found some link which can be useful to you. @nwtgck 
https://philna.sh/blog/2018/10/23/service-workers-beware-safaris-range-request/

**Comment by nwtgck** [comment] 2019-07-29 08:17
@kkanhiya 
> I am still confused why server stops sending video??

I think the Safari disconnects the connection and the Piping Server stop sending video. In my comprehension, If a server supports HTTP Range correctly, the server should return `206 Partial Content` status, but Piping Server doesn't. So Safari rejects the connection and disconnects. 

Unfortunately, streaming in Piping Server, and HTTP-Range-support is conflicted. In the policy of Piping Server, it never stores user data. I think HTTP-Range-support needs data storing to get arbitrary range.

**Comment by kkanhiya** [comment] 2019-07-29 08:21
@nwtgck Today I was trying more things and found that sever stops two times then safari starts to play video as it does in chrome. Kind of strange??

**Comment by nwtgck** [comment] 2019-07-29 08:23
@kkanhiya Do you mean that you should type the send-command twice in Chrome like the following?

```
# twice
cat ray.mp4 | pv | curl -T - -H 'Content-Type: video/mp4' https://piping.ml/myvideo
cat ray.mp4 | pv | curl -T - -H 'Content-Type: video/mp4' https://piping.ml/myvideo
```

**Comment by nwtgck** [comment] 2019-07-29 08:31
@kkanhiya 

In my own experiment, that's a Chrome specification. It seems to require `Content-Type`.  So, the following commands work too.

```bash
# Just send Content-Type
curl -X POST  -H 'Content-Type: video/mp4' https://piping.ml/myvideo
# Streaing video
cat ray.mp4 | curl -T - -H 'Content-Type: video/mp4' https://piping.ml/myvideo
```

**Comment by kkanhiya** [comment] 2019-07-29 08:42
Rajats-MBP:Downloads kibbcom$ cat tester.mp4 | curl -T - -H 'Range:200-2000' https://piping.ml/myvideolive
[INFO] Waiting for 1 receiver(s)...
[INFO] 1 receiver(s) has/have been connected.
[INFO] Start sending to 1 receiver(s)!
[INFO] All receiver(s) was/were closed halfway.
Rajats-MBP:Downloads kibbcom$ cat tester.mp4 | curl -T - -H 'Range:200-2000' https://piping.ml/myvideolive
[INFO] Waiting for 1 receiver(s)...
[INFO] 1 receiver(s) has/have been connected.
[INFO] Start sending to 1 receiver(s)!
[INFO] All receiver(s) was/were closed halfway.
Rajats-MBP:Downloads kibbcom$ cat tester.mp4 | curl -T - -H 'Range:200-2000' https://piping.ml/myvideolive
[INFO] Waiting for 1 receiver(s)...
[INFO] 1 receiver(s) has/have been connected.
[INFO] Start sending to 1 receiver(s)!
[INFO] Sent successfully!


Then video gets played in safari.

**Comment by nwtgck** [comment] 2019-07-29 08:50
@kkanhiya I understand what you did, but I have no idea why it worked and I was surprised.
I tried your commands several times, but I could not play it on Safari on my Mac.

In the implementation of current Piping Server, sender's header of `Range: ooo` is not passed to a receiver. (in this case, the sender is your `curl`. The receiver is your Safari.) So, technically, the curl commands are the same as ` cat tester.mp4 | curl -T - https://piping.ml/myvideolive`.

Could you tell me how big your `test.mp4` is? Maybe, it depends on the size, but I'm not sure.

**Comment by kkanhiya** [comment] 2019-07-29 09:02
tester.mp4 video is of 2.6mb
![videotest](https://user-images.githubusercontent.com/15653799/62035504-9f649980-b20d-11e9-8154-0cf3cb6f9917.gif)

**Comment by nwtgck** [comment] 2019-07-29 09:08
@kkanhiya Thank you so much for recording and submitting your demo video! I'm very surprised. I think this is a great finding. I'd like to know the details.

You seem to play video on HTML. Could you give me your HTML?  Because I play a video directly in Safari, opening <https://piping.ml/myvideolive> directly in the URL box.

**Comment by kkanhiya** [comment] 2019-07-29 09:09
<head>
  <video controls>
    <source src="https://piping.ml/myvideolive" type="video/mp4" />
</video>
</body>

**Comment by kkanhiya** [comment] 2019-07-29 09:11
I made html file as txt. Kindly rename it as .html to make it work.
[index.txt](https://github.com/nwtgck/piping-server/files/3441190/index.txt)

**Comment by nwtgck** [comment] 2019-07-29 09:33
@kkanhiya Finally, I could play on Safari! I can play without HTML. But I have no idea how Safari works.

But I think the following Safari's requests can be helpful to understand Safari in Network tab. I'll look into it.
![image](https://user-images.githubusercontent.com/10933561/62037663-3130ce80-b22f-11e9-90f8-23681f556ff1.png)


![image](https://user-images.githubusercontent.com/10933561/62037618-152d2d00-b22f-11e9-8a3f-94204a1c7497.png)

![image](https://user-images.githubusercontent.com/10933561/62037634-1cecd180-b22f-11e9-88b9-66dc8f35fcf5.png)

![image](https://user-images.githubusercontent.com/10933561/62037646-2413df80-b22f-11e9-910b-690b5aad00c6.png)

**Comment by nwtgck** [comment] 2019-07-29 09:41
@kkanhiya This may be a unique phenomenon in `piping.ml`. I have another Piping Server `ppng.ml`, and I did the same thing, but I could not play it on Safari. Both `piping.ml` and 'ppng.ml' uses different reverse-proxy. That may affect this phenomenon.

**Comment by kkanhiya** [comment] 2019-07-29 10:08
Which reverse-proxy software is being used?? More information can be useful in solving this bug.

**Comment by nwtgck** [comment] 2019-07-29 10:17
@kkanhiya 
* `piping.ml` uses <https://github.com/http-party/node-http-proxy>
* `ppng.ml` uses <https://caddyserver.com/> and <https://github.com/http-party/node-http-proxy>
   - client <=> Caddy <=> node-http-proxy <=> Piping Server

**Comment by kkanhiya** [comment] 2019-07-29 11:12
on uncaughtException TypeError: Cannot read property 'writev' of undefined
   at ServerHttp2Stream._writev (internal/http2/core.js:1356:24)
   at doWrite (_stream_writable.js:395:12)
   at clearBuffer (_stream_writable.js:501:5)
   at onwrite (_stream_writable.js:449:7)
   at WriteWrap.afterDoStreamWrite [as oncomplete] (internal/http2/core.js:1133:9)
   at ServerHttp2Stream.finishStreamDestroy (internal/http2/core.js:1496:12)
   at runCallback (timers.js:794:20)
   at tryOnImmediate (timers.js:752:5)
   at processImmediate [as _immediateCallback] (timers.js:729:5)

Exception on the server logs. Whenever safari disconnects.

**Comment by nwtgck** [comment] 2019-07-29 11:36
@kkanhiya Greate report! You might find Node.js bug?

**Comment by nwtgck** [comment] 2019-07-29 11:39
@kkanhiya I did a quick search and found https://github.com/nodejs/node/issues/16797. The error message looks similar.

**Comment by kkanhiya** [comment] 2019-07-30 03:57
@nwtgck true looks like a node error. I am using node v10.8.0, seems there is no fix to this error

**Comment by nwtgck** [comment] 2019-07-30 06:19
@kkanhiya Do you mean that this Safari issue is caused by another problem, not <https://github.com/nwtgck/piping-server/issues/171#issuecomment-515949251>?

**Comment by kkanhiya** [comment] 2019-07-30 06:21
@nwtgck Either node has not fixed safari problem in v10.8 or there is some either problem.

**Comment by nwtgck** [comment] 2019-07-30 06:50
@kkanhiya I think the latest v10.x is 10.16.0. Are you going to try this version?

![image](https://user-images.githubusercontent.com/10933561/62107002-9fce6480-b2e1-11e9-891b-fe90456ccf8f.png)
(from: https://nodejs.org/en/download/releases/)

**Comment by kkanhiya** [comment] 2019-07-31 07:31
There is no error in the new version of the node but still, the issue is not resolved as we need to fire command 3 times to play on safari.

**Comment by nwtgck** [comment] 2019-07-31 08:12
@kkanhiya Thank you very much for your trying.

I think the issue is under desktop Safari, not Piping Server. As I mentioned, real-time streaming and HTTP Range is a conflicted idea. iOS Safari requires HTTP Range. So, I'd like to close this issue.

iOS Safari requires HTTP Range : <https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6>.

**Closed** 2019-08-07 06:30 UTC
