### ISSUE TITLE
Too early to destroy?

### ISSUE THREAD

**Issue by mooglejp** [nwtgck/piping-server#261] opened 2020-01-07 14:55 UTC
https://github.com/nwtgck/piping-server/blob/0095a039e8695ab4160be6ac8b911fc58f01c61a/src/piping.ts#L472

At this point, I think some readers may still be reading.
Client often fails with error like:
"transfer closed with outstanding read data remaining."

**Comment by nwtgck** [comment] 2020-01-07 15:03
@mooglejp Thanks.

Umm... I think so too. In particular, it is too early in the case of a slow receiver and a fast sender. One thing I'm wondering is I haven't seen the errors so much... I am one of the heavy users of Piping Server.

**Comment by nwtgck** [comment] 2020-01-07 15:06
MYNOTE:
Sender: `seq 1000 | curl -T - https://ppng.ml/s`
Receiver: `curl --limit-rate 1 https://ppng.ml/s`

**Comment by nwtgck** [comment] 2020-01-07 15:14
@mooglejp I think the `destroy()` may be OK because it is called in on("close"), not on("end").

https://github.com/nwtgck/piping-server/blob/0095a039e8695ab4160be6ac8b911fc58f01c61a/src/piping.ts#L468-L476

The server log in a successful case should be like the following.
![image](https://user-images.githubusercontent.com/10933561/71905464-88a67380-31ab-11ea-8c05-9f843dcc62ee.png)

**Comment by mooglejp** [comment] 2020-01-08 05:41
@nwtgck 

Sorry for the lack (and wrong) of information at my first post.
I saw the message below when I was transferring large(>=50MB) file over HTTPS.
`curl: (56) Failure when receiving data from the peer.`
(not `curl: (18) ...`)
And got file that missing last several (kilo)bytes.

After removing [that](https://github.com/nwtgck/piping-server/blob/0095a039e8695ab4160be6ac8b911fc58f01c61a/src/piping.ts#L472) code, the problem seems to be solved.

**Comment by nwtgck** [comment] 2020-01-08 05:56
@mooglejp 

Thank you very much for the investigation. That will contributes to the stability of Piping Server.

I'd like to reproduce in my environment. Could you tell me about your environment?

- Are you using a local or remote Piping Server?
- What is your OS? Linux/macOS/Windows? `curl` and the server run in the same OS?

**Comment by mooglejp** [comment] 2020-01-08 06:45
@nwtgck

> Are you using a local or remote Piping Server?

Remote.
Piping Server is running on docker on Linux on ESXi. (behind NAPT)

> What is your OS? Linux/macOS/Windows?

Docker Host OS: `RancherOS v1.5.4` [see](https://github.com/rancher/os/releases/tag/v1.5.4)
Docker Image: `nwtgck/piping-server:v0.15.5`
Client OS: `Windows10 (1809/1903)`
curl: `7.55.1 (Windows) libcurl/7.55.1 WinSSL`

> curl and the server run in the same OS?

Not same.

**Comment by nwtgck** [comment] 2020-01-08 14:26
@mooglejp 

Thank you very much for the detail. I'd like to know about additional settings.

- You said "file over HTTPS". Does it happen when **HTTP**, not only HTTPS?

**Comment by mooglejp** [comment] 2020-01-08 14:51
@nwtgck 
As far as I tried, It happens only when HTTPS.

**Comment by nwtgck** [comment] 2020-01-08 15:01
@mooglejp Only HTTP...🤔 , very interesting. I'll try to imitate your setting and reproduce the problem.

Maybe, to fix quickly, you can use a reverse proxy to provide HTTPS. Here are an example of reverse proxy settings. They may help to introduce it although the main purpose of each repo is not for providing the SSL/TLS layer.

- <https://github.com/nwtgck/piping-server-http2-docker-compose> (I guess this is easier to introduce it without code change)
- <https://github.com/nwtgck/piping-server-basic-auth-docker-compose>
- <https://github.com/nwtgck/piping-server-load-balancer-docker-compose>

But anyway, I'll reproduce the error.

**Comment by mooglejp** [comment] 2020-01-08 15:39
@nwtgck 

>    https://github.com/nwtgck/piping-server-http2-docker-compose (I guess this is easier because of non-code-change)
>    https://github.com/nwtgck/piping-server-basic-auth-docker-compose
>    https://github.com/nwtgck/piping-server-load-balancer-docker-compose

Wow! Great works!
Thank you for letting me know.

I'll let you know if I get something about occurrence condition.

**Comment by nwtgck** [comment] 2020-01-08 15:41
@mooglejp Great! Could you tell me which one did you use?

**Comment by mooglejp** [comment] 2020-01-08 15:58
Oops. I just marveled at your work.
Sorry for misleading you :cry:
I will try your "piping-server-http2-docker-compose".

**Comment by nwtgck** [comment] 2020-01-08 16:02
@nwtgck Thank you very much! That's no problem. (I think also have a problem with my comprehension...)

**Comment by mooglejp** [comment] 2020-01-08 18:35
@nwtgck 

I tried "piping-server-http2-docker-compose".

Message below appears occasionally while repeating the test.
`curl: (18) transfer closed with ***** bytes remaining to read`

**COMMANDS**
Sender:
`curl.exe --insecure -T pwsh.msi https://192.168.5.5:8443/pwsh`
Receiver:
`curl.exe --insecure https://192.168.5.5:8443/pwsh -o pwsh.msi`
(add `--limit-rate 10240000` if not reproduced)

---
>Remote.
>Piping Server is running on docker on Linux on ESXi. (behind NAPT)

Additionally, The problem appeared when I tried in my LAN.

**Comment by nwtgck** [comment] 2020-01-09 01:31
@mooglejp 

Thank you very much for the detail information. I'll try raw Piping Server to reproduce the problem first.

**Comment by nwtgck** [comment] 2020-01-10 03:20
Currently, I'm trying to reproduce the problem on my machine. First, I'd like to figure out which one has the problem. Here are the candidates.
- Piping Server
- Node.js
- curl
- Docker
- Docker base image
- Server OS
- Client OS
- Combinations of above

**Comment by nwtgck** [comment] 2020-01-10 03:30
## nwtgck's Experiment 1

## Environment

macOS Mojave 10.14.6

```console
$ node -v
v10.18.0
$ npm -v
6.13.6
$ curl --version
curl 7.67.0 (x86_64-apple-darwin18.7.0) libcurl/7.67.0 SecureTransport zlib/1.2.11
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

## Method
- Run Piping Server with self-signed certificates (revision: 2db3e8ffcfd216a24846d557dbd399f45764b221)
- Send infinite random bytes by `curl` over HTTP**S**
- Receive the bytes and discard over HTTP**S**
- The client and server run on the same machine.

### Results

Over 50GB of data has been transferred successfully.
The following animated GIF is the result.
![piping-server-local-https-over-50GB mp4 opt](https://user-images.githubusercontent.com/10933561/72123479-b9053200-33a4-11ea-9f4d-64694fc3eed2.gif)


The problem not reproduced.

---

@mooglejp I'll change a part of the settings and try to reproduce the problem.

**Comment by nwtgck** [comment] 2020-01-10 08:39
## Draft: nwtgck's Experiment 2

### Environments

#### client
macOS Mojave 10.14.6

```console
6.13.6
$ curl --version
curl 7.67.0 (x86_64-apple-darwin18.7.0) libcurl/7.67.0 SecureTransport zlib/1.2.11
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

#### server

Ubuntu 18.04

```console
$ docker -v
Docker version 19.03.5, build 633a0ea838
```

### Method
- Run Piping Server with self-signed certificates Docker image v0.15.5
- Send infinite random bytes by `curl` over HTTP**S**
- Receive the bytes and discard over HTTP**S**

### Results

The following output from `curl` is the result.

TODO: FILL

**Comment by nwtgck** [comment] 2020-01-10 10:07
## nwtgck's Experiment 3

### Environments

#### client

Windows 10 on VirtualBox
VirtualBox Version 6.0.14
<img src="https://user-images.githubusercontent.com/10933561/72144287-aa863d00-33db-11ea-8211-d01c685771a3.png" width="300">

![image](https://user-images.githubusercontent.com/10933561/72144612-15377880-33dc-11ea-8864-9d72bbb98425.png)


#### server

Ubuntu 18.04

```console
$ docker -v
Docker version 19.03.5, build 633a0ea838
```

The client and server not the same machines, but they are on the same LAN.

### Method
- Random 5GB file was created by `fsutil file createnew my5GB 5368709000`
- Run Piping Server with self-signed certificates on the server
  - Docker image piping-server:v0.15.5, image ID: 059238feb5ce
- Send infinite random bytes by `curl` over HTTP**S** on the client
  - `curl -kT my5GB.dat ...`
- Receive the bytes and discard over HTTP**S** on the client
  - `curl -k ... > mydiscard`

### Results

The following output from `curl` of the receiver is the result.

![image](https://user-images.githubusercontent.com/10933561/72144522-e3261680-33db-11ea-88e7-0a1acf2555dc.png)


Over 5GB of data was transferred successfully.
The problem not reproduced.

--- 

@mooglejp I'll change a part of the settings and try to reproduce the problem. When you have advice or suggestion, please feel free to tell me.

**Comment by nwtgck** [comment] 2020-05-22 16:16
I think you are right.

`receiver.res.connection.destroy();` closes receiver's connection earlier. I may fix this issue.

**Comment by nwtgck** [comment] 2020-05-23 15:03
@mooglejp  Hi!

I fixed the early destroy issue in https://github.com/nwtgck/piping-server/commit/399aa3ccbaa2bf146bb5636b070821e38e9f3cb4. I hope this fix solves your problem.

**Comment by nwtgck** [comment] 2020-11-30 14:48
The commit above should have fixed the problem. Please feel free to open it when you have the problem.

**Closed by nwtgck** 2020-11-30 14:48 UTC
